package org.poptarticus.FunActivitys.Pages;

class allBooks {

    // Member variable (properties about the object)
    String[] mPuns = {
            "I wondered why the baseball was getting bigger. Then it hit me.",
            "Did you hear about the guy whose whole left side was cut off?  He's all right now.",
            "I'm reading a book about anti-gravity. It's impossible to put down.",
            "I used to be a banker but I lost interest",
            "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
            "It's not that the man did not know how to juggle, he just didn't have the balls to do it.",
            "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
            "Have you ever tried to eat a clock? It's very time consuming.",
            "A man just assaulted me with milk, cream and butter. How dairy.",
            "My friend's bakery burned down last night. Now his business is toast.",
            "I don't trust these stairs because they're always up to something.",
            "When William joined the army he disliked the phrase 'fire at will'.",
            "He drove his expensive car into a tree and found out how the Mercedes bends.",
            "Need an ark to save two of every animal? I noah guy.",
            "The man who survived mustard gas and pepper spray is now a seasoned veteran.",
            "I couldn't quite remember how to throw a boomerang, but eventually it came back to me.",
            "What is the difference between a nicely dressed man on a tricycle and a poorly dressed man on a bicycle? A tire.",
            "I used to have a fear of hurdles, but I got over it.",
            "To write with a broken pencil is pointless.",
            "Atheists don't solve exponential equations because they don't believe in higher powers.",
            "When the window fell into the incinerator, it was a pane in the ash to retrieve.",
            "Police were called to a daycare where a three-year-old was resisting a rest.",
            "Show me a piano falling down a mineshaft and I'll show you A-flat minor.",
            "I'm glad I know sign language, it's pretty handy.",
            "I relish the fact that you've mustard the strength to ketchup to me.",
            "A bicycle can't stand on its own because it is two-tired.",
            "Atheism is a non-prophet organization.",
            "Claustrophobic people are more productive thinking outside the box.",
            "A small boy swallowed some coins and was taken to a hospital. When his grandmother telephoned to ask how he was a nurse said 'No change yet'.",
            "The roundest knight at king Arthur's round table was Sir Cumference.",
            "Time flies like an arrow. Fruit flies like a banana.",
            "Show me a piano falling down a mineshaft and I'll show you A-flat minor.",
            "To write with a broken pencil is pointless.",
            "A bicycle can't stand on its own because it is two-tired.",
            "Those who get too big for their britches will be exposed in the end.",
            "When a clock is hungry it goes back four seconds.",
            "A chicken crossing the road is poultry in motion.",
            "If you don't pay your exorcist you get repossessed.",
            "What's the definition of a will? It's a dead giveaway.",
            "The man who fell into an upholstery machine is fully recovered.",
            "Every calendar's days are numbered.",
            "Bakers trade bread recipes on a knead to know basis.",
            "When the electricity went off during a storm at a school the students were de-lighted.",
            "I used to be a tap dancer until I fell in the sink.",
            "He wears glasses during math because it improves division.",
            "She was only a whisky maker but he loved her still.",
            "She had a boyfriend with a wooden leg, but broke it off.",
            "Those who jump off a Paris bridge are in Seine.",
            "It wasn't school John disliked it was just the principal of it.",
            "It's better to love a short girl than not a tall.",
            "There was once a cross-eyed teacher who couldn't control his  pupils.",
            "A grenade thrown into a kitchen in France would result in Linoleum Blownapart.",
            "A boiled egg in the morning is hard to beat.",
            "The one who invented the door knocker got a No-bell prize.",
            "Old power plant workers never die they just de-generate.",
            "There was a ghost at the hotel, so they called for an inn spectre.",
            "With her marriage she got a new name and a dress.",
            "The short fortune-teller who escaped from prison was a small medium at large",
            "Some Spanish government employees are Seville servants.",
            "He drove his expensive car into a tree and found out how the Mercedes bends.",
            "Show me someone in denial and I'll show you a person in Egypt up to their ankles.",
            "Two peanuts were walking in a tough neighborhood and one of them was a-salted.",
            "When cannibals ate a missionary they got a taste of religion.",
            "When an actress saw her first strands of gray hair she thought she'd dye.",
            "He often broke into song because he couldn't find the key.",
            "Marathon runners with bad footwear suffer the agony of defeat.",
            "Driving on so many turnpikes was taking its toll.",
            "To some - marriage is a word ... to others - a sentence.",
            "Old lawyers never die they just lose their appeal.",
            "In democracy its your vote that counts. In feudalism its your count that votes.",
            "Atheism is a non-prophet organization",
            "It was an emotional wedding. Even the cake was in tiers.",
            "Old skiers never die -- they just go down hill.",
            "A cardboard belt would be a waist of paper.",
            "Local Area Network in Australia: the LAN down under.",
            "When the TV repairman got married the reception was excellent.",
            "An office with many people and few electrical outlets could be in for a power struggle.",
            "How do you make antifreeze? Steal her blanket.",
            "A small boy swallowed some coins and was taken to a hospital. When his grandmother telephoned to ask how he was a nurse said 'No change yet'.",
            "A pediatrician is a doctor of little patients.",
            "Nylons give women a run for their money.",
            "Talking to her about computer hardware I make my mother board.",
            "Ancient orators tended to Babylon.",
            "The best way to stop a charging bull is to take away his credit card.",
            "If you give some managers an inch they think they're a ruler.",
            "Two silk worms had a race. They ended up in a tie.",
            "He had a photographic memory that was never developed.",
            "Old burglars never die they just steal away.",
            "A lawyer for a church did some cross-examining.",
            "Chronic illegal parkers suffer from parking zones disease.",
            "Some people don't like food going to waist..",
            "A cannibal's favourite game is 'swallow the leader'.",
            "You feel stuck with your debt if you can't budge it.",
            "Girls who don't get asked out as often as their friends could feel out-dated.",
            "We were so poor when I was growing up we couldn't even afford to pay attention.",
            "A pet store had a bird contest with no perches necessary.",
            "A backwards poet writes inverse.",
            "If a lawyer can be disbarred can a musician be denoted or a model deposed?",
            "Once you've seen one shopping center you've seen a mall.",
            "When the smog lifts in Los Angeles, U C L A.",
            "A plateau is a high form of flattery.",
            "When chemists die, we barium.",
            "A long knife has been invented that cuts four loaves of bread at a time called a four loaf cleaver.",
            "When the wheel was invented, it caused a revolution.",
            "Two robbers with clubs went golfing, but they didn't play the fairway.",
            "Seven days without a pun makes one weak.",
            "A circus lion won't eat clowns because they taste funny.",
            "A toothless termite walked into a tavern and said, 'Is the bar tender here?'",
            "Did you hear about the fire at the circus? The heat was intense.",
            "A tattoo artist has designs on his clients.",
            "Santa's helpers are subordinate clauses.",
            "A lot of money is tainted. It taint yours and it taint mine.",
            "When they bought a water bed, the couple started to drift apart.",
            "What you seize is what you get.",
            "Gardeners always know the ground rules.",
            "Some people's noses and feet are build backwards: their feet smell and their noses run.",
            "Two banks with different rates have a conflict of interest.",
            "A successful diet is the triumph of mind over platter.",
            "What do you call cheese that is not yours? Nacho Cheese.",
            "When a new hive is done bees have a house swarming party.",
            "Looting a drugstore is called Pillaging",
            "Never lie to an x-ray technician. They can see right through you.",
            "Old programmers never die, they just can't C as well.",
            "A music store had a small sign which read: Bach in a Minuet.",
            "Long fairy tales have a tendency to dragon.",
            "Visitors to Cuba are usually Havana good time.",
            "A bachelor is a guy who is footloose and fiancée-free.",
            "A ditch digger was entrenched in his career.",
            "A girl and her boyfriend went to a party as a barcode. They were an item.",
            "A criminal's best asset is his lie ability.",


    };


    String[] mFact = {
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Google hired a camel to create the Street View of a desert.",
            "Mobile phones have 18 times more bacteria than toilet handles.",
            "Krusty the Clown was originally created to be Homer Simpsons secret identity.",
            "Lady Gaga once baught $1000 worth of pizza for fans waiting in line for her.",
            "The puppeteers who animated the raptors in 'Jurassic Park' had to take a 6 week long class on how to move like a dinosaur.",
            "There's town in Texas called Earth and it's the only place on Earth officially named Earth.",
            "You could cover the Great Wall of China 8 times Nutella sold in a year.",
            "The famous Windows start up sound was composed using a Mac.",
            "Oxford University is older than the Aztec Empire.",
            "Blue whales are so enormmous that a small child could swim through it's veins.",
            "A pound of houseflies contains more protein as compared to a pound of beef.",
            "More people speak English in China than the United States.",
            "In space, you cannot cry because there is no gravity to make the tears flow.",
            "Man is the only mammal that willingly delays sleep.",
            "Male kangaroos flex their biceps to impress females.",
            "IN Australia Burger King is called Hungry Jacks.",
            "A group of pandas is called an embarrassment.",
            "The U.S. Government spent $277,000 on pickle research in 1993.",
            "A new study suggests that eating chocolate could improve the brain's ability to do Mathematics.",
            "It rains diamonds on Saturn and Jupiter", "Will Smith's first name is actually Willard, not William",
            "The Walking Dead cast and crew holds death dinner's for any characters who get killed off the show",
            "THe bio-Bus is a bus service in the UK that is powered by poop",
            "There's a law in South Korea that bans under 16s from playing online games between midnight and 6am, called the 'Shutdown Law'.",
            "The chills you get when you listen to music is called musical frission.",
            "At YouTube Headquarters, employees can either take the elevator, stairs or slide.",
            "Rat's can't throw up' that's why rat poison works.",
            "Most of the dust underneath your bed is actually your own dead skin.",
            "In Mexico, artists can pay their taxes with artwork",
            "Marge Simpson was originally supposed to have bunny ears underneath her blue hair",
            "Google hired a camel to create the Street View of a desert",
            "Banging your head against a wall burns 150 calories an hour.",
            "In the UK, it is illegal to eat mince pies on Christmas Day!",
            "Pteronophobia is the fear of being tickled by feathers!",
            "When hippos are upset, their sweat turns red.",
            "A flock of crows is known as a murder.",
            "Facebook Addiction Disorder is a mental disorder identified by Psychologists.",
            "The average woman uses her height in lipstick every 5 years.",
            "29th May is officially Put a Pillow on Your Fridge Day.",
            "Cherophobia is the fear of fun.",
            "Human saliva has a boiling point three times that of regular water.",
            "If you lift a kangaroos tail off the ground it cant hop.",
            "Hyphephilia are people who get aroused by touching fabrics.",
            "The person who invented the Frisbee was cremated and made into frisbees after he died!"
            , "During your lifetime, you will produce enough saliva to fill two swimming pools.",
            "An eagle can kill a young deer and fly away with it.",
            "Polar bears can eat as many as 86 penguins in a single sitting.",
            "King Henry VIII slept with a gigantic axe beside him.",
            "Bikinis and tampons invented by men.",
            "If Pinokio says My Noes Will Grow Now, it would cause a paradox. Details here.",
            "Heart attacks are more likely to happen on a Monday.",
            "If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!",
            "An average persons yearly fast food intake will contain 12 pubic hairs.",
            "The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
            "There is a species of spider called the Hobo Spider.",
            "A toaster uses almost half as much energy as a full-sized oven.",
            "A baby spider is called a spiderling.",
            "You cannot snore and dream at the same time.",
            "The following can be read forward and backwards: Do geese see God?",
            "A baby octopus is about the size of a flea when it is born.",
            "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
            "In Uganda, 50% of the population is under 15 years of age.",
            "Hitlers mother considered abortion but the doctor persuaded her to keep the baby.",
            "Arab women can initiate a divorce if their husbands dont pour coffee for them.",
            "Recycling one glass jar saves enough energy to watch TV for 3 hours.",
            "Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.",
            "Catfish are the only animals that naturally have an odd number of whiskers.",
            "Facebook, Skype and Twitter are all banned in China."
            , "95% of people text things they could never say in person.",
            "The Titanic was the first ship to use the SOS signal.",
            "About 8,000 Americans are injured by musical instruments each year.",
            "The French language has seventeen different words for surrender.",
            "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
            "Bob Dylans real name is Robert Zimmerman.",
            "A crocodile cant poke its tongue out :p",
            "Sea otters hold hands when they sleep so they dont drift away from each other.",
            "A small child could swim through the veins of a blue whale.",
            "Bin Ladens death was announced on 1st May 2011. Hitlers death was announced on 1st May 1945."

    };

    // Member variable (properties about the object)
    String[] mIcebreaker = {

            "Whats the greatest bit of advice a parent or mentor has given you?",
            "What technology innovation made the most impact on your life?",
            "Describe a challenging situation youve been in and tell how you resolved it?",
            "How would you spend one million dollars?",
            "Who is your hero, and why?",
            "Tell us your earliest childhood memory.",
            "Who was your favorite teacher in school and how did s/he impact you?",
            "If you could choose an age to remain forever, which age would you choose?",
            "What is one important skill every person should have?",
            "What is your favorite sport to watch?",
            "If you had one free hour each day, how would you use it?",
            "What was the best thing that happened to you this weekend? This month? This year?",
            "If you could go anywhere in the world on vacation, where would you go?",
            "How would your friends describe you?",
            "What would be the ultimate gift for you to receive?",
            "If you could live anywhere in the world, where would it be?",
            "Would you rather be invisible or be able to read minds?",
            "If you had a time machine, what point in the past or future would you visit?",
            "Name two things you consider yourself to be very good at.",
            "If you could live in any period of history, when would it be?",
            "Whats the greatest bit of advice a parent or mentor has given you?",
            "What technology innovation made the most impact on your life?",
            "Describe a challenging situation youve been in and tell how you resolved it?",
            "How would you spend one million dollars?",
            "Who is your hero, and why?",
            "Tell us your earliest childhood memory.",
            "Who was your favorite teacher in school and how did s/he impact you?",
            "If you could choose an age to remain forever, which age would you choose?",
            "What is one important skill every person should have?",
            "What is your favorite sport to watch?",
            "If you had one free hour each day, how would you use it?",
            "What was the best thing that happened to you this weekend? This month? This year?",
            "If you could go anywhere in the world on vacation, where would you go?",
            "How would your friends describe you?",
            "What would be the ultimate gift for you to receive?",
            "If you could live anywhere in the world, where would it be?",
            "Would you rather be invisible or be able to read minds?",
            "If you had a time machine, what point in the past or future would you visit?",
            "Name two things you consider yourself to be very good at.",
            "If you could live in any period of history, when would it be?",
            "What is the best perk that you have had at a job?",
            "Describe one experience youve had where you took a huge leap of faith.",
            "What is the best vacation youve ever had?",
            "Where in the world have you been that you thought was paradise?",
            "What is the meaning of your name?",
            "If you could host a talk show, who would be your first guest?",
            "What is one word that you would use to describe your team?",
            "Share a personal fact no one would ever guess about you.",
            "What is the most important personal attribute that you bring to your job?",
            "What is one thing you admire most about the person to the right of you?",
            "What would you like to be known for?",
            "What fictional place would you like to visit?",
            "Share a funny incident in your life.",
            "What is your favorite outdoor activity?",
            "Who would you like to exchange roles with?",
            "What is one of the things on your bucket list?",
            "Describe yourself in 3 words.",
            "What do you enjoy doing to relieve stress?",
            "If you were famous, what would you be famous for?",
            "What do you think you will be doing 20 years from now?",
            "If you didnt need a job, were healthy, and had plenty of time, what would you do?",
            "What do you consider your greatest achievement?",
            "What is a recent book that you have enjoyed? Why?",
            "What would you do with your 15 minutes of fame?",
            "Over the course of your life, how many cities have you lived in and which was your favorite?",
            "What was going on during the happiest time of your life?",
            "If you could only take one physical item with you on a deserted island, what it would be?",
            "Whats one sentence youd like to hear from your boss?",
            "If you could have a dinner with someone who is alive or dead, who would it be and why?",
            "What are you going to do when you retire?"

    };

    // Member variable (properties about the object)
    String[] mDadJoke = {

            "Dad, did you get a haircut? No I got them all cut.",
            "What do you call a Mexican who has lost his car? Carlos.",
            "Dad, can you put my shoes on? No, I don’t think they’ll fit me.",
            "Can I watch the TV? Dad: Yes, but don’t turn it on.",
            "I would avoid the sushi if I was you. It’s a little fishy.",
            "What do you call a fake noodle? An Impasta.",
            "You know, people say they pick their nose, but I feel like I was just born with mine.",
            "Every time I hurt myself, even to this day, my dad says, ‘The good news is..it’ll feel better when it quits hurting.'”",
            "What’s brown and sticky? A stick.",
            "Want to hear a joke about paper? Never mind it’s tearable.",
            "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
            "I’ll call you later!”- Please don’t do that. I’ve always asked you to call me Dad!”",
            "Q: Why did the cookie cry? A: Because his father was a wafer so long!",
            "What did the mountain climber name his son? Cliff.",
            "This graveyard looks overcrowded. People must be dying to get in there.",
            "My dad literally told me this one last week: ‘Did you hear about the guy who invented Lifesavers? They say he made a mint.’”",
            "Whenever the cashier at the grocery store asks my dad if he would like the milk in a bag he replies, ‘No, just leave it in the carton!’”",
            "I got so angry the other day when I couldn’t find my stress ball.",
            "If I had a dime for every book I’ve ever read, I’d say: Wow, that’s coincidental.”",
            "I’m not indecisive. Unless you want me to be.",
            "How many apples grow on a tree? All of them.",
            "How does a penguin build it’s house? Igloos it together.",
            "Me: ‘Dad, make me a sandwich!’ Dad: ‘Poof, You’re a sandwich!’”",
            "I heard there was a new store called Moderation. They have everything there",
            "A steak pun is a rare medium well done.",
            "How can you tell if a ant is a boy or a girl? They’re all girls, otherwise they’d be uncles.”",
            "Milk is also the fastest liquid on earth – its pasteurized before you even see it",
            "What’s Forrest Gump’s password? 1forrest1”",
            "The only thing worse than having diarrhea is having to spell it.",
            "I asked my friend to help me with a math problem. He said: Don’t worry; this is a piece of cake.” I said: No, it’s a math problem.”",
            "I keep trying to lose weight, but it keeps finding me.",
            "I don’t play soccer because I enjoy the sport. I’m just doing it for kicks.",
            "Did I tell you the time I fell in love during a backflip? I was heels over head.",
            "I used to work in a shoe recycling shop. It was sole destroying.",
            "Why do you never see elephants hiding in trees? Because they’re so good at it.",
            "Where did the one-legged waitress work? IHOP!",
            "What happened when the two antennas got married? Well, the ceremony was kinda boring, but the reception was great!",
            "What did one snowman say to the other one?  Do you smell carrots?”",
            "How do you make a tissue dance?  You put a little boogie in it!",
            "Why did the blonde stare at the orange juice container?  It said concentrate!",
            "If your nose runs and your feet smell, you are built upside down!",
            "I went to buy some camouflage trousers the other day, but I couldn’t find any.",
            "Q: How do you organize an outer space party? A: You planet.",
            "Q: What do you call a belt with a watch on it?A: A waist of time.",
            "What kind of shoes does a thief wear? Sneakers",
            "A jumper cable walks into a bar. The bartender says, I’ll serve you, but don’t start anything.”",
            "An invisible man marries an invisible woman. The kids were nothing to look at either.",
            "I went to a seafood disco last week… and pulled a mussel.",
            "Did you hear about the man who stole a calendar? He got 12 months.",
            "A man woke up in a hospital after a serious accident. He shouted, Doctor, doctor, I can’t feel my legs!” The doctor replied, I know you can’t I’ve cut off your arms!”",
            "Do you know where you can get chicken broth in bulk? The stock market.",
            "What did the ocean say to the shore? Nothing, it just waved.",
            "What’s ET short for? Because he’s only got little legs.”",
            "Why do crabs never give to charity? Because they’re shellfish.",
            "What do you call an Argentinian with a rubber toe? Roberto",
            "What do you call a man with no nose and no body? Nobody nose.”",
            "I cut my finger chopping cheese, but I think that I may have greater problems.",
            "What do you call a fish with no eyes? A fshhhh.",
            "What do you call a man with no arms and no legs lying in front of your door? Matt.”",
            "My cat was just sick on the carpet, I don’t think it’s feline well.",
            "I dreamed about drowning in an ocean made out of orange soda last night. It took me a while to work out it was just a Fanta sea.",
            "Without geometry life is pointless.",
            "A termite walks into a bar and asks Is the bar tender here?”",
            "I gave all my dead batteries away today… Free of charge.",
            "I needed a password eight characters long so I picked Snow White and the Seven Dwarfs.",
            "I am terrified of elevators. I’m going to start taking steps to avoid them.",
            "What’s the advantage of living in Switzerland? Well, the flag is a big plus.",
            "Why did the octopus beat the shark in a fight? Because it was well armed.",
            "A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.",
            "I’ve deleted the phone numbers of all the Germans I know from my mobile phone. Now it’s Hans free.",
            "Last night me and my girlfriend watched three DVDs back to back. Luckily I was the one facing the TV.",
            "Q: What did daddy spider say to baby spider? A: You spend too much time on the web.",
            "How much does a hipster weigh? An instagram.",
            "What do you call a group of killer whales playing instruments? An Orca-stra.",
            "Why was the big cat disqualified from the race? Because it was a cheetah.",
            "Bicycles can’t stand on their own, they’re two tired.",
            "Just watched a documentary about beavers… It was the best damn program I’ve ever seen.",
            "Breaking news! Energizer Bunny arrested – charged with battery",
            "How do you make holy water? You boil the hell out of it.”",
            "A Sandwich walks into a bar, the bartender says Sorry, we don’t serve food here”",
            "Doctor, I’ve broken my arm in several places” Doctor Well don’t go to those places.”",
            "I’m on a whiskey diet. I’ve lost three days already.",
            "Why did the Clydesdale give the pony a glass of water?",
            "Because he was a little horse!”",
            "There’s a new type of broom out, it’s sweeping the nation.",
            "Atheism is a non-prophet organisation.",
            "Slept like a log last night … woke up in the fireplace.",
            "We were getting fast food when the lady at the window said, ‘Any condiments?’ My dad responded, ‘Compliments? You look very nice today!’”",
            "What cheese can never be yours? Nacho cheese.",
            "A police officer caught two kids playing with a firework and a car battery. He charged one and let the other one off.",
            "I’m reading a book on the history of glue – can’t put it down.",
            "Did you hear about the kidnapping at school? It’s fine, he woke up.",
            "I went to the zoo the other day, there was only one dog in it. It was a shitzu.",
            "What did the daddy tomato say to the baby tomato? A: catch up!",
            "Q: What’s 50 Cent’s name in Zimbabwe? A: 400 Million Dollars.",
            "Q: What did baby corn say to mama corn? A: Where’s popcorn?",
            "What do you call a cow with no legs? Ground beef.",
            "What did the Buffalo say to his little boy when he dropped him off at school? Bison.",
            "So a duck walks into a pharmacy and says Give me some chap-stick… and put it on my bill”",
            "Why did the scarecrow win an award? Because he was outstanding in his field.",
            "Why did the girl smear peanut butter on the road? To go with the traffic jam.",
            "Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan.",
            "Why don’t seagulls fly over the bay? Because then they’d be bay-gulls!",
            "Two peanuts were walking down the street. One was a salted.”",
            "What do you do when a blonde throws a grenade at you? Pull the pin and throw it back.",
            "How do you make a hankie dance? Put a little boogie in it.",
            "Where does batman go to the bathroom? The batroom.",
            "What’s the difference between an African elephant and an Indian elephant? About 5000 miles",
            "I’m on a seafood diet… I see food and I eat it.",
            "A man walks into a bar and orders helicopter flavor chips. The barman replies sorry mate we only do plain”",
            ": Commissar! Commissar! The troops are revolting! Commissar: Well, you’re pretty repulsive yourself.",
            "What do you call a sheep with no legs? A cloud.",
            "I knew I shouldn’t have ate that seafood. Because now I’m feeling a little… Eel",
            "What did the 0 say to the 8? Nice belt.",
            "Why are skeletons so calm? Because nothing gets under their skin.",
            "Why don’t skeletons ever go trick or treating? Because they have nobody to go with.",
            "Why do scuba divers fall backwards into the water? Because if they fell forwards they’d still be in the boat.",
            "Have you ever heard of a music group called Cellophane? They mostly wrap.",
            "What kind of magic do cows believe in? MOODOO.",
            "Why does Superman gets invited to dinners? Because he is a Supperhero.",
            "Hold on, I have something in my shoe”  I’m pretty sure it’s a foot”",
            "Dad I’m hungry … Hi hungry” I’m dad",
            "When phone ringing Dad says ‘If it’s for me don’t answer it.",
            "I asked my dad for his best dad joke and he said, ‘You.’”",
            "Where’s the bin? Dad: I haven’t been anywhere!"


    };


}
